spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://userModel
          predicates:
            - Path=/users/**
          filters:
            StripPrefix=1

        - id: singer-service
          uri: lb://singerModel
          predicates:
            - Path=/singer/**
          filters:
            - StripPrefix=1

        - id: music-service
          uri: lb://musicModel
          predicates:
            - Path=/music/**
          filters:
            - StripPrefix=1

        - id: album-service
          uri: lb://albumModel
          predicates:
            - Path=/album/**
          filters:
            - StripPrefix=1